### PR TITLE
Support directories

### PR DESCRIPTION
**Pull request by owenstranathan**
The diff looks crazy because I put things in functions.
But all this does is allows you to specify a directory of files and runs the templater over every file it finds in that directory (it use's `find` so maybe I should allow users to send args through to find, like max-depth and exclusions?)

Also adds a delimiter option so you can put a delimiter, which defaults to `\n---\n` you can nullify the delimiter default by using option `-d ""`

PS
Thanks for writing this guys, all I wanted was simple templates and every template solution on offer from other languages was just too heavy and clunky. This is great

### CODE REVIEW

**Comment by johanhaleby** [comment]
woah, this is a big PR :) It's unfortunate that there are no test cases. Should it still be backward compatible to your knowledge?

**Comment by owenstranathan** [comment]
@johanhaleby As far as I know it still works as before. The changes actually aren't that big. I just separated the main functionality into a `main` function and the argument parsing into a `parse_args` function. Then I check if the template source is a file or directory and call main either on the file or on every file in the directory respectively. The diff makes it look more extreme than it is because indentation. 

That said. it's totally possible that I broke something, but all my manually testing works fine. 

If I get some time later I'll write up a few tests and include them in the PR

**Comment by owenstranathan** [comment]
@johanhaleby You actually had a regression from your upstream and the `{{VAR=$OTHER}}` was not
working. It was working however in your upstream. I hand merged you're changes into your upstream and re-added my own changes, I also improved your changes so that you load variable files without sourcing, that way you can use `.env` (which I also added a default support for) files and also allows you to count on those variables being set in subshell (because they're exported)

I improved the testing (I copied your upstream's test and expanded on it)

The diff is even bigger now, but it's not such a complicated script. I encourage you to pull down [my fork](https://github.com/owenstranthan/bash-templater) and play with it. Let me know if you have questions/concerns.

**Comment by owenstranathan** [comment]
Whoops looks like I messed up your README when I did that merge. I'll fix

**Comment by owenstranathan** [comment]
I'm closing this because in my testing and tinkering I've changed so much that it's really become too big.

**Comment by johanhaleby** [comment]
Sorry for not responding for such a long time, I'm on vacation. Could we perhaps split up the PR into multiple parts if it makes sense?

**Pull request closed without merging**
